// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

function redactAuthHeaders(headers: Headers) {
  const redacted: Record<string, string> = {};
  headers.forEach((value, key) => {
    const lower = key.toLowerCase();
    redacted[key] = lower === 'apikey' || lower === 'authorization'
      ? value
        ? '<present:redacted>'
        : '<empty>'
      : value;
  });
  return redacted;
}

function isAuthDiagnosticUrl(url: string) {
  return /\/auth\/v1\/(recover|token|verify|signup)/.test(url);
}

async function diagnosticFetch(input: RequestInfo | URL, init?: RequestInit) {
  const request = new Request(input, init);
  const shouldLog = isAuthDiagnosticUrl(request.url);
  if (shouldLog) {
    console.log('[Supabase auth request]', {
      url: request.url,
      method: request.method,
      headers: redactAuthHeaders(request.headers),
      body: typeof init?.body === 'string' ? init.body : '<non-string-or-empty>',
    });
  }

  try {
    const response = await fetch(request);
    if (shouldLog) {
      let body = '<unreadable>';
      try {
        body = await response.clone().text();
      } catch (error) {
        body = `<failed to read response body: ${error instanceof Error ? error.message : String(error)}>`;
      }
      console.log('[Supabase auth response]', {
        url: response.url || request.url,
        status: response.status,
        statusText: response.statusText,
        headers: redactAuthHeaders(response.headers),
        body,
      });
    }
    return response;
  } catch (error) {
    if (shouldLog) {
      console.error('[Supabase auth request failed]', {
        url: request.url,
        method: request.method,
        error,
        name: (error as { name?: unknown })?.name,
        message: (error as { message?: unknown })?.message,
        stack: (error as { stack?: unknown })?.stack,
        cause: (error as { cause?: unknown })?.cause,
      });
    }
    throw error;
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: diagnosticFetch,
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

